/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Approve: typeof import('./../components/SimpleProcessDesigner/nodes/approve.vue')['default']
    BarageItem: typeof import('./../components/Barrage/BarageItem.vue')['default']
    BarrageItem: typeof import('./../components/Barrage/BarrageItem.vue')['default']
    Camera: typeof import('./../components/camera/src/camera.vue')['default']
    Close: typeof import('./../components/SimpleProcessDesigner/Close.vue')['default']
    ConfigGlobal: typeof import('./../components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    CopyTaskNode: typeof import('./../components/SimpleProcessDesigner/nodes/copyTaskNode.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EndNode: typeof import('./../components/SimpleProcessDesigner/nodes/endNode.vue')['default']
    ExclusiveNode: typeof import('./../components/SimpleProcessDesigner/nodes/exclusiveNode.vue')['default']
    Header: typeof import('./../components/Header/index.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    NodeHandler: typeof import('./../components/SimpleProcessDesigner/NodeHandler.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleProcessDesigner: typeof import('./../components/SimpleProcessDesigner/index.vue')['default']
    SimpleProcessNode: typeof import('./../components/SimpleProcessDesigner/simpleProcessNode.vue')['default']
    StartNode: typeof import('./../components/SimpleProcessDesigner/nodes/startNode.vue')['default']
  }
}
